### ISSUE TITLE
gulp start:prod not working

### ISSUE THREAD

**Issue by aswath-veersoft** [matthias-schuetz/angular2-seed#10]
Hi, 
I ran gulp:prod, then I got the blank page in the chrome browser.
I looked at the console, found the following message
DevTools failed to parse SourceMap: http://localhost:8081/src/shim.min.js.map

Thanks.

**Comment by matthias-schuetz** [comment]
SourceMaps are disabled in the `tsconfig.json` by default. You can generate them by changing the setting to
`"sourceMap": true`
and recompile. Or you can disabled JavaScript SourceMaps in Chrome (developer tools/settings/preferences/sources/ so you won't get that warning.
But still the warning doesn't stop the app from running, it's just a warning. So your error is somewhere else. In order to run the prod server, you need to run `gulp start:prod`.

**Comment by aswath-veersoft** [comment]
Yes, I did gulp start:prod.
It shows blank page.  

I am using windows 7.

Thanks.

**Comment by matthias-schuetz** [comment]
I see. Do you see any other errors in the console, besides the SourceMap warning?
And have you checked the contents of your `dist` folder, does it look correctly? There should be an `index.html` in it and a `src/app.min.js` which should be about 509 KB large.

Remember that the prod server is running on `http://localhost:8081/` instead of `8080`.

**Comment by Cyral** [comment]
I'm having the same issue, the real error is:

Uncaught ReferenceError: exports is not defined
    at app.min.js:13
    at app.min.js:13

Here is the difference between the app.min.js files from my own version and the demo:

http://i.imgur.com/wpkHCro.png
http://i.imgur.com/8tMre1a.png

There is an error in the build process:
gulp-typescript: tsProject.src() takes no arguments - Use gulp.src(..) if you need to specify a glob

So replacing tsProject.src with gulp.src leads to another error which looks relevant to the code that is missing (notice how my version requires app.module.ngfactory in the result)

```
[18:02:31] Starting 'dev:compile:typescript'...
app\src\bootstrap.aot.ts(2,36): error TS2307: Cannot find module '../../app-aot/app/src/app.module.ngfactory'.
```

I'd appreciate the help. Using gulp for many other things and this is the most promising angular2 gulp seed I've seen.

**Comment by matthias-schuetz** [comment]
Thanks Cyral for the detailed information! I was able to fix it and updated the seed.
I could have thought of it myself since the issues were caused by version updates of the packages. So I changed some version numbers (TypeScript, types and some Angular dependencies) and it works again. To be safe, simply delete your existing `node_modules` directory inside your seed, get the latest seed and `npm install` again.
