### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Miss-Git** [matthias-schuetz/angular2-seed#4]
While using gulp I'm having these typescript semantic errors:
[09:27:48] Starting 'dev:compile:typescript'...
app\src\app.component.spec.e2e.ts(1,1): error TS2304: Cannot find name 'describe'.
app\src\app.component.spec.e2e.ts(3,5): error TS2304: Cannot find name 'beforeEach'.
app\src\app.component.spec.e2e.ts(4,9): error TS2304: Cannot find name 'browser'.
app\src\app.component.spec.e2e.ts(7,5): error TS2304: Cannot find name 'it'.
app\src\app.component.spec.e2e.ts(8,9): error TS2304: Cannot find name 'expect'.
app\src\app.component.spec.e2e.ts(8,16): error TS2304: Cannot find name 'browser'.
[09:27:49] TypeScript: 6 semantic errors

Also when running project these:

_system.conf.js:1 Uncaught SyntaxError: Unexpected token <_

_Failed to parse SourceMap: http://localhost:8080/src/vendor/node_modules/Reflect.js.map_

What is wrong?

**Comment by matthias-schuetz** [comment]
The TypeScript semantic errors are related to the missing typings, so you need to install Typings globally first (I also updated the Readme.md) via `npm install typings -g` and afterwards you need to do a `typings install` in your seed folder. When running Gulp again, there shouldn't occur any errors.

The second issue is related to a missing source map: this Angular 2 seed doesn't make use of source maps so they won't be generated or copied. That's why Chrome is giving you this message. You can turn off this warning in the Chrome settings (disable the source maps setting, it's only for developers who like source map support). If you want to use source maps, you need to copy the source maps of all node_modules via Gulp and you'll have to set the "sourceMap" option to "true" in the tsconfig.json.

**Comment by Miss-Git** [comment]
Thanks. What about the Uncaught SyntaxError ?

**Comment by Miss-Git** [comment]
Also, I ran the two commands you said and I get these Err.s on typings install:
http://uupload.ir/files/xxui_err.png

**Comment by matthias-schuetz** [comment]
OK it seems you're a bit unlucky, not your fault so far.
The `typings install` didn't work as expected, there's a network error. So you should just retry and run `typings install` again. Try it a few times, it may depend on your network situation.

The Uncaught SyntaxError is about a missing file, in your case this would be `system.conf.js` which cannot be found. Did you change something in the file/directory structure? The system configuration should be inside the app/ folder directly. If you run Gulp and access the site via http://localhost:8080, open the developer tools and head over to the "Network" panel. Hit refresh and check the `system.conf.js` on the left side. Click on the entry, on mouseover it should say:

http://localhost:8080/system.conf.js

And on the right side in the "Response" tab, you should see the JavaScript code of the file. If that isn't the case, the file can't be found so you need to check your file structure if it's there.
