### ISSUE TITLE
Separate dist and source files 

### ISSUE THREAD

**Issue by pvamshi** [matthias-schuetz/angular2-seed#6]
I don't know if I am doing something wrong but having js and ts files together is very difficult to work on. I use vim and I need to rely on compiling ts to js . 
I keep opening js files instead of ts files . 

We need to separate dist files and source files. 
I will work on that , if you like it we can merge . 
Also I might add `jade` support. I like jade more than html .

**Comment by matthias-schuetz** [comment]
No, you're nothing doing wrong, the parallel TS/JS files are on purpose. Transpiling the JS files into a separate folder means that you have to do copy all other files (HTML, CSS, etc.) to that directory after every transpilation. I wanted to prevent this since. Other IDEs like WebStorm or Visual Studio collapse TS/JS files into one item, so you won't see the JS files in the files window.
But it's no problem to add the functionality, I will add a Gulp variable to transpile JS files into a separate directory (I will publish a seed update to RC7 before).

The support of Jade should also be no problem, I'd liked to have the seed minimalistic but I'll take a look at Jade since it's a more modern apporach. I'll give you a response in a short time!

**Comment by pvamshi** [comment]
Thanks for the positive reaction :) 👍

**Comment by matthias-schuetz** [comment]
OK, so I've just committed the RC7 updated and with that, 2 new Gulp tasks are now included for creating a separate dev directory. If you run `gulp start:dev:separate`, a separate directory will be created and also all JS/CSS files will be compiled into that place. A new file watcher for that case is also included so you won't have any parallel JS/CSS files anymore when using this task. You can configure the separate directory options in the `dev.separateDest` config options.
I will take a look at Jade next week.

**Comment by matthias-schuetz** [comment]
OK finally I found the time to add support for Pug templates (former Jade). Since I want to provide flexibility to everyone, I just created a branch for Pug. So you can find the whole seed with Pug templates in the [pug branch](https://github.com/matthias-schuetz/angular2-seed/tree/pug).

**Comment by pvamshi** [comment]
This is great . Thanks for the help
