### ISSUE TITLE
AOT Compiling

### ISSUE THREAD

**Issue by piers-shepherd-sift** [matthias-schuetz/angular2-seed#8]
Hey there.

First of all I'd like to thank you for the work you have put into this project and sharing it. It has been a valuable asset while learning Angular2. So thank you very much.

I encountered what I think might be an error, although I may be wrong.

When running gulp build:prod I kept getting permission errors when the AOT scripts were running.

"-bash: node_modules/.bin/ngc: Permission denied"

After a bit of fiddling I was able to get the aot compiler working by changing the following in package.json:

from
----
`
  "scripts": {
    "aot": "node_modules/.bin/ngc -p tsconfig-aot.json",
    "aot-rollup": "node_modules/.bin/rollup -c aot-rollup-config.js"
  },`

to
----

`  "scripts": {
    "aot": "node node_modules/.bin/ngc -p tsconfig-aot.json",
    "aot-rollup": "node node_modules/.bin/rollup -c aot-rollup-config.js"
  },`

Note that I had to place 'node' before each script.

What I believe was happening is the js file was trying to be run in the command line, but by adding 'node' to the front I was forcing it to be executed by nodejs.

I'm curios if this has happened to you?

Anyways. Thanks again.

**Comment by matthias-schuetz** [comment]
Thanks for finding out that problem! I copied the npm script from the official Angular 2 AoT cookbook. The issue came up because the command works well on Windows but doesn't on Linux/OS X.
I updated the `package.json` and `gulpfile.js` and tested it in Windows and Linux. It should work fine now, so you can pull at try if you like.

Thanks again for your attention!
